### ISSUE TITLE
Feature request: allow character indices for variables

### ISSUE THREAD

**Issue by kkmann** [dirkschumacher/ompr#166]
Hey,

I was just wondering whether or not it would be possible to allow variable creation using arbitrary indices, e.g., 

    MIPModel() %>% add_variable(x[ind], ind in c("hi", "ho"))

I feel that this would sometimes help making model definition a bit more 'verbose'...

**Comment by dirkschumacher** [comment]
Yes that is something that makes sense. I am planning to write a new "backend" that streamlines the evaluation and interpretation of these expressions and allows for character indexes as well.

**Comment by kkmann** [comment]
Great looking forward to it! Let me just say, taking the idea of JuMP to R is just amazing - I guess the final syntax might be even more readable in R because of the mighty NSE features. Just worried about performance a bit - for large scale assignment problems (millions of binary variables), `ompr` is already quite slow. It might be worth thinking about parallelizing model creation...

**Comment by dirkschumacher** [comment]
Thanks. I know `ompr` is slow for large models. I initially developed it to test the idea and focused on an API that is usable first. The next step is to keep the api, but enhance the underlying model generation code so that you can build huge models with it. Have non-linear models and so on. There are a couple of options now and I believe performance with state of the art modelling languages can be reached. However I just develop that stuff as a hobby after work, so I cannot make any promises - but I guess that's the case with most OS projects ;)
