### ISSUE TITLE
Parallel Processing

### ISSUE THREAD

**Issue by pnick9** [dirkschumacher/ompr#212]
Hi Dirk,

I am trying to built a very similar to TSP problem but with the opposite direction (demand points to facilities) and with 563 demand points of which 3 can be selected as facilities. I was wondering if it is possible to use ompr with parallel computing in order to speed up the process. Would it be possible?

**Comment by dirkschumacher** [comment]
Some solvers, especially the commercial ones implement some sort of parallelization. Does that answer your question? In `ompr` parallel processing _could_ be used to speed up model generation, but I hope the `MILPModel` will eventually be fast enough, so that modelling will not be the bottleneck.

Does that answer your question?
