### ISSUE TITLE
MILPModel: correct usage of matrices

### ISSUE THREAD

**Issue by etesio** [dirkschumacher/ompr#238]
Hi there, I am trying to represent a constraint involving a matrix as follows:

Q[m,h] <= A[m,h]

with something like 
```
A <- data.frame()
for (m in 1:5) {
  for (h in 1:3) {
    A[m,h] <- 2.*m + h
  }
}
colnames(A) <- 1:3

model <- MILPModel() %>%
  add_variable(Q[m,h], m=1:5, h=1:3, type="continuous") %>%
  add_constraint(Q[m,h] <= A[m,h], m=1:5, h=1:3)
```

but I am crashing against

`cannot coerce class ‘structure("LinearVariableCollection", package = "ompr")’ to a data.frame`

From the docs it seems I am not getting something about the `colwise` trick? The snippet above would seem pretty "intuitive", and indeed using `MIPModel` it works... or am I missing something else?

Thanks for any help

**Comment by hugolarzabal** [comment]
MILP model ara faster tham MIP because they use vectors instead of single variables.

A MIP model understand  Q[m,h] <= A[m,h] as 
Q[1,1] <= A[1,1] and Q[1,2] <= A[1,2] ... and Q[5,3] <= A[5,3]

On the other and, the MILP model understand Q[m,h] <= A[m,h] as
c(Q[1,1], Q[1,2]... Q[5,3]) < A[m,h]

So your constant A[m,h] needs to be a vector as well with the same number of values as Q[m,h]
