### ISSUE TITLE
Objective function does not work with linear coefficients

### ISSUE THREAD

**Issue by kamilchlosta** [dirkschumacher/ompr#271]
I try to apply the model for solving my MILP problem. There are four power generation units: GT, U2, U3, U4, each has a minimum and maximum power Pmin and Pmax. Each unit has a cost-generating linear characteristic as f(y)=ay+b. The objective is to pick the most cost-effective units from these to cover a heat demand. When I write the model this way:

```
heat_demand <- 400
C <- data.frame(p_unit=c("GT","U2","U3","U4"),
                Pmin=c(35, 30, 70, 70),
                Pmax=c(70, 115, 140, 250),
                a=c(2,4,5,6),
                b=c(1,3,6,8))
unit_nrs <- as.numeric(length(C$p_unit))

model1 <- MIPModel() %>% 
  add_variable(y[i], i = 1:unit_nrs, type = "continuous") %>% 
  add_variable(x[i], i = 1:unit_nrs, type = "binary") %>%
  set_bounds(y[1], lb = C$Pmin[1], ub = C$Pmax[1]) %>% 
  set_bounds(y[2], lb = C$Pmin[2], ub = C$Pmax[2]) %>% 
  set_bounds(y[3], lb = C$Pmin[3], ub = C$Pmax[3]) %>% 
  set_bounds(y[4], lb = C$Pmin[4], ub = C$Pmax[4]) %>% 
  set_objective(sum_expr((C$a[i]*y[i]+C$b[i])*x[i], i = 1:unit_nrs), "max") %>%
  add_constraint(sum_expr(x[i]*y[i], i = 1:unit_nrs) == heat_demand) %>% 
  add_constraint(y[i]>=C$Pmin[i], i = 1:unit_nrs) %>%
  add_constraint(y[i]<=C$Pmax[i], i = 1:unit_nrs) %>% 
  solve_model(with_ROI(solver = "glpk"))
get_solution(model1, x)
get_solution(model1, y)  
```

I get "Error: The objective is probably non-linear. Currently, only linear functions are supported.". 1. Any ideas how can I make this work?
2. Is there a better way to write down set_bounds() (similar to add_constraint with indexes)?

**Comment by hugolarzabal** [comment]
1 You cannot multiplicate variables in a linear model, you are only allowed to use + and - when you create relations between variables.

The way I understand it, your variable x means that the power unit is used if 1 and not used if 0.
There are several ways to model that in a linear way, here is one solution:

Do not set any bound to y and use the following constraints:
 `y[i] >= x[i] * C$Pmin[i]`
 `y[i] <= x[i] * C$Pmax[i]`
That way, if x = 1, y is forced to be between Pmin and Pmax and if x = 0, y is forced to 0.
Then you can use y alone in the objective function and the heat constraint.

2 I don't think that you can use bounds depending on the indexes in set_bounds but you can use add_constraint for that.
I think it is actually better for the readability of your model to use add_constraint because a bound which depend on index is actually a constraint that should be established clearly.

**Comment by kamilchlosta** [comment]
Thank you! I am forever grateful. It works like a charm now. Keep up the good work! If anyone is interested how does it look like now:
```

model1 <- MIPModel() %>% 
  add_variable(y[i], i = 1:unit_nrs, type = "continuous") %>% 
  add_variable(x[i], i = 1:unit_nrs, type = "binary") %>%
  set_objective(sum_expr(C$a[i]*y[i]+x[i]*C$b[i], i = 1:unit_nrs), "max") %>%
  add_constraint(sum_expr(y[i], i = 1:unit_nrs) == heat_demand) %>% 
  add_constraint(y[i]>=x[i]*C$Pmin[i], i = 1:unit_nrs) %>%
  add_constraint(y[i]<=x[i]*C$Pmax[i], i = 1:unit_nrs) %>% 
  solve_model(with_ROI(solver = "glpk"))

operating_units <- data.frame(x=c(model1$solution[1:unit_nrs]),y=c(model1$solution[(unit_nrs+1):(unit_nrs*2)]), row.names = 1:unit_nrs)
optimal_income <- as.numeric(model1$objective_value)


```
Best regards!
