### ISSUE TITLE
Define MILP model using matrix for objective

### ISSUE THREAD

**Issue by djhurio** [dirkschumacher/ompr#279]
Thanks a lot for the package!

I have quite simple problem to solve. I can define it as MIP model. It gives correct result.

```
MIPModel() %>%
  add_variable(x[n, v], n = 1:N, v = 1:V, type = "binary") %>%
  set_objective(sum_expr(d[n, v] * x[n, v], n = 1:N, v = 1:V), "min") %>%
  add_constraint(sum_expr(x[n, v], v = 1:V) == 1L, n = 1:N) %>%
  add_constraint(sum_expr(x[n, v], n = 1:N) == y[v], v = 1:V)
```

`d` is a numeric matrix with the same dimension as `x`.
`y` is a numeric vector.

However it gets very slow or unsolvable for large problems. So I am looking to translate the problem as MILP model. MILP should be much faster.

The problem is - I can not figure out how to write correctly the objective using a matrix for a MILP model.

    set_objective(sum_expr(d[n, v] * x[n, v], n = 1:N, v = 1:V), "min")

I have tried

    set_objective(sum_expr(as.numeric(d) * x[n, v], n = 1:N, v = 1:V), "min")

or

    set_objective(sum_expr(d[x]), "min")

The model is defined, but the result is not optimal. I am missing here something obviously. I have tried stable and dev versions of the package. Any hints are very welcome.

**Comment by hugolarzabal** [comment]
Hello,
In a MILP model, you cannot use a matrix in the model. That is because the MILP model use vectors to create the model faster. When you give him d[n, v], the model translate it as d[1:N, 1:V] and is expecting a vector with all the values of d in the right order. 
If d is a matrix, d[1:N, 1:V] gives an error in R.

In order to pass the information of the paramter to the model, you need to use a function that will accept vectors as input and also return a vector as output.

[This vignette](https://dirkschumacher.github.io/ompr/articles/milp-modelling.html) show how to create a function to use in the objective. (in the extract model solution part)

According to the vignette, a function like this should work (d is your matrix):
```
f_d <- function(i, j) {
  vapply(seq_along(i), function(k) d[i[k], j[k]], numeric(1L))
}
```
Then you should use colwise(f_d(n, v)) in the objective instead of d[n,v]

**Comment by djhurio** [comment]
@hugolarzabal , thank you very much for your help! It works. However, I have to admit the solution is not intuitive.
